# Generated by Django 5.2.17 on 2026-08-25 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0005_systemsettings_remove_candidate_profile_data_and_more",
        ),
        migrations.swappable_dependency(
            settings.AUTH_USER_MODEL
        ),
    ]

    operations = [

        # ========================================================
        # CANDIDATE.profile_data ALREADY EXISTS IN DATABASE
        #
        # We update Django's migration STATE only.
        # We DO NOT create the database column again.
        # ========================================================
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name="candidate",
                    name="profile_data",
                    field=models.JSONField(
                        default=dict,
                        blank=True,
                    ),
                ),
            ],
        ),

        # ========================================================
        # CREATE USER PROFILE
        # ========================================================
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),

                (
                    "phone",
                    models.CharField(
                        max_length=30,
                        blank=True,
                        default="",
                    ),
                ),

                (
                    "profile_data",
                    models.JSONField(
                        default=dict,
                        blank=True,
                    ),
                ),

                (
                    "profile_image",
                    models.ImageField(
                        upload_to="profiles/",
                        blank=True,
                        null=True,
                    ),
                ),

                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                    ),
                ),

                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                    ),
                ),

                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]