# Generated by Django 5.2.17 on 2026-08-25 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_userprofile_profile_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('employer_name', models.CharField(blank=True, default='', max_length=200)),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('immediate_superior', models.CharField(blank=True, default='', max_length=200)),
                ('position', models.CharField(blank=True, default='', max_length=200)),
                ('start_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('end_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('reason_for_leaving', models.TextField(blank=True, default='')),
                ('job_description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_history', to='core.candidate')),
            ],
        ),
    ]
