# Generated by Django 5.2.17 on 2026-09-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_hr_workflow_profile_and_inviter'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='application_type',
            field=models.CharField(choices=[('macro_kiosk', 'Macro Kiosk'), ('insitemy', 'InsiteMy')], default='macro_kiosk', max_length=30),
        ),
    ]
